# Generated by Django 3.1.5 on 2021-05-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perpustakaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('no_hp', models.CharField(max_length=13)),
                ('kelas', models.CharField(max_length=10)),
                ('judul', models.CharField(max_length=30)),
                ('penulis', models.CharField(max_length=20)),
                ('penerbit', models.CharField(max_length=20)),
                ('jumlah_buku', models.IntegerField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
